services:
  app:
    build: .
    command: ["--help"]
    environment:
      - PYTHONUNBUFFERED=1
      - PROXY_HOST=tinyproxy
    volumes:
      - .:/code # Código
      - ./result_files:/code/result_files # Persistencia para archivos
      - ./sqlite_dbs:/code/sqlite_dbs # Persistencia para SQLite
    working_dir: /code
    depends_on: [mysql, postgres, tinyproxy]

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: etl
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: etl
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tinyproxy:
    image: vimagick/tinyproxy:latest
    restart: unless-stopped
    environment:
      - LISTEN_PORT=8888
      - ALLOWED=0.0.0.0/0
      - CONNECT_PORTS=80,443
    ports:
      - "8888:8888"

# Volúmenes nombrados que persisten fuera del contenedor
volumes:
  mysql_data:
  postgres_data:
